theme: jekyll-theme-midnight
title: Nighthawk CSA
description: "This GitHub project provides Advance Placement Computer Science A (AP-CSA) code and training.  The page you are viewing is a GitHub Pages website and is contained within the master branch of the project.   Cloning the GitHub Project (nighthawk_csa) provides both GitHub Pages website and code to support a Java-Spring website.  Using the Java-Spring code includes activities and procedures helps to develop, build, and deploy a Spring Web Server using Java as the backend."
email: "nighthawkcodingsociety@gmail.com"
webserver: "csa.nighthawkcodingsociety.com"
twitter: "twitter.com/NighthawkCoding"
