theme: jekyll-theme-midnight
baseurl: /
title: Nighthawk CSA
description: "This GitHub project provides Advance Placement Computer Science 'A' (AP-CSA) code and training, it is a Java-Spring Web project.  The page you are viewing is a 'GitHub Pages' website and is contained within the master branch of the same project.   Cloning the GitHub Project provides both Java-Spring webserver and GitHub Pages code.  Explore this page for activities. including procedures to develop, build, and deploy a Web Servers in two ways."
email: "nighthawkcodingsociety@gmail.com"
webserver: "csa.nighthawkcodingsociety.com"
twitter: "twitter.com/NighthawkCoding"
